#!/usr/bin/env python3
"""Generate SA&BOO AutoCAD layer CSV, LISP and change-log templates."""
from __future__ import annotations
import csv, pathlib

LAYERS = [
    ("I-WALL-FULL-N", 7, "0.35", "Continuous", "Yes", "cut walls / main partitions"),
    ("I-WALL-LITE-N", 8, "0.18", "Continuous", "Yes", "low partitions / glass / lightweight outlines"),
    ("I-WALL-DEMO-D", 1, "0.18", "DASHED", "Yes", "demolition walls"),
    ("I-DOOR-PANL-N", 3, "0.25", "Continuous", "Yes", "door panels"),
    ("I-DOOR-SWNG-N", 3, "0.13", "Continuous", "Yes", "door swing arcs"),
    ("I-WIND-GLAZ-N", 4, "0.18", "Continuous", "Yes", "windows/glazing"),
    ("I-FURN-FIXD-N", 2, "0.25", "Continuous", "Yes", "fixed furniture/millwork"),
    ("I-FURN-LOOS-N", 9, "0.13", "Continuous", "Yes", "loose FF&E reference"),
    ("I-FLOR-FINI-N", 6, "0.13", "Continuous", "Yes", "floor finish boundaries/patterns"),
    ("I-CEIL-EDGE-N", 5, "0.18", "Continuous", "Yes", "ceiling edges and soffits"),
    ("I-CEIL-GRID-N", 8, "0.09", "Continuous", "Yes", "ceiling grid/light guides"),
    ("E-LITE-FIXT-N", 30, "0.18", "Continuous", "Yes", "lighting fixtures"),
    ("E-SWCH-SYMB-N", 30, "0.18", "Continuous", "Yes", "switches"),
    ("E-POWR-OUTL-N", 1, "0.18", "Continuous", "Yes", "sockets/power/data outlets"),
    ("P-PLMB-FIXT-N", 140, "0.18", "Continuous", "Yes", "sanitary fixtures/drains"),
    ("M-HVAC-DIFF-N", 151, "0.18", "Continuous", "Yes", "diffusers, vents, AC"),
    ("I-HATCH-CUT", 8, "0.09", "Continuous", "Yes", "cut hatches / material hatches"),
    ("I-HATCH-MATL", 9, "0.09", "Continuous", "Yes", "material pattern/hatch"),
    ("I-ANNO-DIMS", 2, "0.18", "Continuous", "Yes", "dimensions"),
    ("I-ANNO-TEXT", 7, "0.18", "Continuous", "Yes", "general notes/text"),
    ("I-ANNO-LEAD", 2, "0.18", "Continuous", "Yes", "leaders"),
    ("I-ANNO-TAGS", 4, "0.18", "Continuous", "Yes", "room/material/door tags"),
    ("I-ANNO-SYMB", 4, "0.18", "Continuous", "Yes", "section/elevation/detail symbols"),
    ("I-AXIS-GRID", 8, "0.13", "CENTER", "Yes", "axis/grid lines"),
    ("I-REV-CLOUD-RXX", 1, "0.25", "Continuous", "Yes", "revision clouds, rename per revision"),
    ("I-REV-DELT-RXX", 1, "0.25", "Continuous", "Yes", "delta triangles/revision marks"),
    ("I-TTLB-LINE", 7, "0.25", "Continuous", "Yes", "title block/borders"),
    ("I-TTLB-TEXT", 7, "0.18", "Continuous", "Yes", "title block text"),
    ("X-BASE-ARCH", 8, "0.09", "Continuous", "Yes", "base building xref geometry"),
    ("X-UNDERLAY", 8, "0.05", "Continuous", "Yes", "consultant underlays"),
    ("NPLT-GUIDE", 6, "0.05", "Continuous", "No", "guides/construction lines"),
    ("NPLT-VPORT", 6, "0.00", "Continuous", "No", "layout viewports"),
]

HEADER = ["Layer", "Color", "Lineweight_mm", "Linetype", "Plot", "Use"]

def write_csv(path: pathlib.Path) -> None:
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        w.writerows(LAYERS)

def write_lisp(path: pathlib.Path) -> None:
    lines = [
        "; SA&BOO AutoCAD layer setup generated by sa-boo-autocad-construction-standard",
        "; Load with APPLOAD or paste into AutoCAD command line / MCP execute_lisp.",
        "(defun c:SABOO_LAYERS (/ make-layer)",
        "  (defun make-layer (name color lw ltype plot /)",
        "    (if (not (tblsearch \"LTYPE\" ltype))",
        "      (command \"_.-LINETYPE\" \"_Load\" ltype \"acad.lin\" \"\"))",
        "    (if (not (tblsearch \"LAYER\" name))",
        "      (command \"_.-LAYER\" \"_New\" name \"\"))",
        "    (command \"_.-LAYER\" \"_Color\" (itoa color) name \"\")",
        "    (command \"_.-LAYER\" \"_Ltype\" ltype name \"\")",
        "    (command \"_.-LAYER\" \"_LWeight\" lw name \"\")",
        "    (if (= plot \"No\")",
        "      (command \"_.-LAYER\" \"_Plot\" \"No\" name \"\")",
        "      (command \"_.-LAYER\" \"_Plot\" \"Yes\" name \"\"))",
        "  )",
    ]
    for name, color, lw, ltype, plot, _use in LAYERS:
        lines.append(f'  (make-layer "{name}" {color} "{lw}" "{ltype}" "{plot}")')
    lines += [
        "  (setvar \"CELTSCALE\" 1)",
        "  (setvar \"LTSCALE\" 50)",
        "  (setvar \"PSLTSCALE\" 1)",
        "  (setvar \"DIMASSOC\" 2)",
        "  (princ \"\\nSA&BOO layers created/updated. Run REGEN if linetypes need refresh.\")",
        "  (princ)",
        ")",
        "(c:SABOO_LAYERS)",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def write_scr(path: pathlib.Path) -> None:
    lines = ["-LAYER"]
    for name, color, lw, ltype, plot, _use in LAYERS:
        lines += ["New", name, "Color", str(color), name, "Ltype", ltype, name, "LWeight", lw, name, "Plot", plot, name]
    lines += [""]
    path.write_text("\n".join(lines), encoding="utf-8")

def write_change_log(path: pathlib.Path) -> None:
    rows = [
        ["Rev", "Date", "Sheet", "Area", "Change Description", "Reason/Source", "Requested By", "Drawn", "Checked", "Approved", "Issue Package"],
        ["R00", "2026-06-22", "A101", "All", "First issue", "Initial construction drawing issue", "Client", "", "", "", "20260622_R00"],
    ]
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        csv.writer(f).writerows(rows)

def write_sheet_index(path: pathlib.Path) -> None:
    rows = [
        ["Sheet No", "Sheet Title", "Scale", "Stage", "Current Rev", "Date", "File Name", "Status"],
        ["A000", "图纸目录 / Drawing Index", "N/A", "CD", "R00", "2026-06-22", "20260622_PROJECT_I_A000_Index-CD_R00.dwg", "Issued"],
        ["A101", "平面布置图 / Plan", "1:50", "CD", "R00", "2026-06-22", "20260622_PROJECT_I_A101_Plan-CD_R00.dwg", "Issued"],
    ]
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        csv.writer(f).writerows(rows)

def main() -> None:
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="assets", help="Output directory")
    args = p.parse_args()
    out = pathlib.Path(args.out).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    write_csv(out / "samboo_layer_standard.csv")
    write_lisp(out / "create_samboo_layers.lsp")
    write_scr(out / "create_samboo_layers.scr")
    write_change_log(out / "change_log_template.csv")
    write_sheet_index(out / "sheet_index_template.csv")
    print(f"Generated CAD standard assets in {out}")

if __name__ == "__main__":
    main()
